layout_spectrum: 0.9661654
color:
  saturation: 0.7419624
  brandStrength: 0.0923804
  lightness: 0.16058
  rhythmicContrast: 0.9376421
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.5870032
name: JENJA
