collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2185821
  brandStrength: 0.245435
  lightness: 0.2346938
  brandColors:
    - '#584C50'
    - '#EEEECC'
    - '#EB7A68'
    - '#014973'
    - '#83807F'
  rhythmicContrast: 0.2282491
typography_spectrum: 0.5870032
layout_spectrum: 0.9661654
name: JENJA
